# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_fbh4enbns2/clone/recipe, last modified Mon Mar  4 03:01:51 2024
# ------------------------------------------------

package:
  name: annotated-types
  version: 0.6.0
source:
  sha256: 563339e807e53ffd9c267e99fc6d9ea23eb8443c08f112651963e24e22f84a5d
  url: https://pypi.io/packages/source/a/annotated_types/annotated_types-0.6.0.tar.gz
build:
  number: '0'
  script: /var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_fbh4enbns2/croot/annotated-types_1709542919423/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py312hecd8cb5_0
requirements:
  host:
    - bzip2 1.0.8 h6c40b1e_5
    - ca-certificates 2023.12.12 hecd8cb5_0
    - editables 0.3 py312hecd8cb5_0
    - expat 2.5.0 hcec6c5f_0
    - hatchling 1.21.1 py312hecd8cb5_0
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_0
    - ncurses 6.4 hcec6c5f_0
    - openssl 3.0.13 hca72f7f_0
    - packaging 23.1 py312hecd8cb5_0
    - pathspec 0.10.3 py312hecd8cb5_0
    - pip 23.3.1 py312hecd8cb5_0
    - pluggy 1.0.0 py312hecd8cb5_1
    - python 3.12.2 hd58486a_0
    - readline 8.2 hca72f7f_0
    - setuptools 68.2.2 py312hecd8cb5_0
    - sqlite 3.41.2 h6c40b1e_0
    - tk 8.6.12 h5d9f67b_0
    - trove-classifiers 2023.10.18 py312hecd8cb5_0
    - tzdata 2024a h04d1e81_0
    - wheel 0.41.2 py312hecd8cb5_0
    - xz 5.4.6 h6c40b1e_0
    - zlib 1.2.13 h4dc903c_0
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
    - pytest -v tests
  imports:
    - annotated_types
  requires:
    - pip
    - pytest
  source_files:
    - tests
about:
  description: 'This package provides metadata objects which can be used to represent
    common constraints such as upper and lower

    bounds on scalar values and collection sizes, a Predicate marker for runtime checks,
    and descriptions of how we

    intend these metadata to be interpreted. In some cases, we also note alternative
    representations which do not

    require this package.

    '
  dev_url: https://github.com/annotated-types/annotated-types
  doc_url: https://github.com/annotated-types/annotated-types
  home: https://github.com/annotated-types/annotated-types
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Reusable constraint types to use with typing.Annotated
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: fb03070a-9f40-4ec9-8acb-084fc8b6084d
  recipe-maintainers:
    - Zac-HD
    - mattwthompson
    - samuelcolvin
  remote_url: git@github.com:AnacondaRecipes/annotated-types-feedstock.git
  sha: 1cd1d7c79fcaee88c1cd10e446127ce035e8cd88
