# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_8amnrgen5s/clone/recipe, last modified Tue Apr 30 15:58:13 2024
# ------------------------------------------------

package:
  name: lz4-c
  version: 1.9.4
source:
  fn: lz4-1.9.4.tar.gz
  sha256: 0b0e3aa07c8c063ddf40b082bdf7e37a1562bda40a0ff5272957f3e987e0e54b
  url: https://github.com/lz4/lz4/archive/v1.9.4.tar.gz
build:
  number: '1'
  run_exports:
    - lz4-c >=1.9.4,<1.10.0a0
  string: hcec6c5f_1
requirements:
  build:
    - cctools_osx-64 949.0.1 hc7db93f_25
    - clang 14.0.6 hecd8cb5_1
    - clang-14 14.0.6 default_hd95374b_1
    - clang_osx-64 14.0.6 hb1e4b1b_0
    - clangxx 14.0.6 default_hd95374b_1
    - clangxx_osx-64 14.0.6 hd8b9576_0
    - compiler-rt 14.0.6 hda8b6b8_0
    - compiler-rt_osx-64 14.0.6 h8d5cb93_0
    - ld64_osx-64 530 h70f3046_25
    - ldid 2.1.5 hc58f1be_3
    - libclang-cpp14 14.0.6 default_hd95374b_1
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - libllvm14 14.0.6 h91fad77_3
    - llvm-tools 14.0.6 he0576d7_3
    - make 4.2.1 h3efe00b_1
    - tapi 1000.10.8 ha1b3eb9_0
    - zlib 1.2.13 h4dc903c_0
  host:
    - libcxx 14.0.6 h9765a3e_0
  run:
    - libcxx >=14.0.6
about:
  description: 'LZ4 is lossless compression algorithm, providing compression speed
    at 400

    MB/s per core (0.16 Bytes/cycle). It features an extremely fast decoder,

    with speed in multiple GB/s per core (0.71 Bytes/cycle). A high compression

    derivative, called LZ4_HC, is available, trading customizable CPU time for

    compression ratio. LZ4 library is provided as open source software using a

    BSD license.

    '
  dev_url: https://github.com/lz4/lz4
  doc_url: https://github.com/lz4/lz4/blob/dev/README.md
  home: https://lz4.github.io/lz4/
  license: BSD-2-Clause
  license_family: BSD
  license_file: lib/LICENSE
  summary: Extremely Fast Compression algorithm
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 8a77723a-ac08-4e83-9c16-e7838134a4bb
  recipe-maintainers:
    - mingwandroid
    - rmax
    - wesm
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/lz4-c-feedstock.git
  sha: 45537caf4f5443bf05cd61697e4cc857567e2aee
