# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: simdjson
  version: 3.10.1
source:
  sha256: 1e8f881cb2c0f626c56cd3665832f1e97b9d4ffc648ad9e1067c134862bba060
  url: https://github.com/simdjson/simdjson/archive/v3.10.1.tar.gz
build:
  number: 0
  run_exports:
    - simdjson >=3.10.1,<3.11.0a0
  string: h1962661_0
requirements:
  build:
    - bzip2 1.0.8 h6c40b1e_6
    - c-ares 1.19.1 h6c40b1e_0
    - ca-certificates 2024.11.26 hecd8cb5_0
    - cctools_osx-64 949.0.1 hc7db93f_25
    - clang 14.0.6 hecd8cb5_1
    - clang-14 14.0.6 default_hd95374b_1
    - clang_osx-64 14.0.6 hb1e4b1b_0
    - clangxx 14.0.6 default_hd95374b_1
    - clangxx_osx-64 14.0.6 hd8b9576_0
    - cmake 3.26.4 hbb7d193_0
    - compiler-rt 14.0.6 hda8b6b8_0
    - compiler-rt_osx-64 14.0.6 h8d5cb93_0
    - expat 2.6.4 h6d0c2b6_0
    - krb5 1.20.1 h428f121_1
    - ld64_osx-64 530 h70f3046_25
    - ldid 2.1.5 hc58f1be_3
    - libclang-cpp14 14.0.6 default_hd95374b_1
    - libcurl 8.9.1 h3a17b82_0
    - libcxx 14.0.6 h9765a3e_0
    - libedit 3.1.20230828 h6c40b1e_0
    - libev 4.33 h9ed2024_1
    - libffi 3.4.4 hecd8cb5_1
    - libllvm14 14.0.6 h26321d7_4
    - libmpdec 4.0.0 h46256e1_0
    - libnghttp2 1.57.0 h9beae6a_0
    - libssh2 1.11.1 h3a17b82_0
    - libuv 1.48.0 h46256e1_0
    - llvm-tools 14.0.6 h91fad77_4
    - lz4-c 1.9.4 hcec6c5f_1
    - ncurses 6.4 hcec6c5f_0
    - ninja 1.12.1 hecd8cb5_0
    - ninja-base 1.12.1 h1962661_0
    - openssl 3.0.15 h46256e1_0
    - python 3.13.1 h1ec50cd_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 hca72f7f_0
    - rhash 1.4.3 h04015c4_0
    - sqlite 3.45.3 h6c40b1e_0
    - tapi 1000.10.8 ha1b3eb9_0
    - tk 8.6.14 h4d00af3_0
    - tzdata 2024b h04d1e81_0
    - xz 5.4.6 h6c40b1e_1
    - zlib 1.2.13 h4b97444_1
    - zstd 1.5.6 h138b38a_0
  host:
    - libcxx 14.0.6 h9765a3e_0
  run:
    - libcxx >=14.0.6
test:
  commands:
    - test -f "${PREFIX}/include/simdjson.h"
    - test -f "${PREFIX}/lib/libsimdjson${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/cmake/simdjson/simdjson-config.cmake"
    - cmake -G Ninja -S test/ -B build/ -D TEST_TARGET=simdjson ${CMAKE_ARGS}
    - cmake --build build/
    - cmake --build build --target test
  files:
    - test/*
  requires:
    - clangxx_osx-64 14.*
    - cmake
    - ninja
about:
  description: 'JSON is everywhere on the Internet.

    Servers spend a *lot* of time parsing it. We need a fresh approach.

    The simdjson library uses commonly available SIMD instructions and

    microparallel algorithms to parse JSON 2.5x faster than anything else out there.

    '
  dev_url: https://github.com/simdjson/simdjson/
  doc_url: https://simdjson.github.io/simdjson/
  home: https://simdjson.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Parsing gigabytes of JSON per second
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 4f92b6ee-c1b5-4e00-acec-bd7a2fb97af0
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - elbaro
  remote_url: git@github.com:AnacondaRecipes/simdjson-feedstock.git
  sha: 751e747ff65ed7f4c599e297a43a84ae810be04c
