# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_f2kfyv072k/clone/recipe, last modified Mon Apr 15 10:27:11 2024
# ------------------------------------------------

package:
  name: frozendict
  version: 2.4.2
source:
  fn: frozendict-2.4.2.tar.gz
  sha256: 741779e1d1a2e6bb2c623f78423bd5d14aad35dc0c57e6ccc89e54eaab5f1b8a
  url: https://pypi.org/packages/source/f/frozendict/frozendict-2.4.2.tar.gz
build:
  number: '0'
  script: python -m pip install . --no-deps --no-build-isolation -v
  script_env:
    - FROZENDICT_PURE_PY=1
  string: py312hecd8cb5_0
requirements:
  build: []
  host:
    - bzip2 1.0.8 h6c40b1e_5
    - ca-certificates 2024.3.11 hecd8cb5_0
    - expat 2.5.0 hcec6c5f_0
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_0
    - ncurses 6.4 hcec6c5f_0
    - openssl 3.0.13 hca72f7f_0
    - pip 23.3.1 py312hecd8cb5_0
    - python 3.12.2 hd58486a_0
    - readline 8.2 hca72f7f_0
    - setuptools 68.2.2 py312hecd8cb5_0
    - sqlite 3.41.2 h6c40b1e_0
    - tk 8.6.12 h5d9f67b_0
    - tzdata 2024a h04d1e81_0
    - wheel 0.41.2 py312hecd8cb5_0
    - xz 5.4.6 h6c40b1e_0
    - zlib 1.2.13 h4dc903c_0
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
    - pytest -v test
  imports:
    - frozendict
  requires:
    - pip
    - pytest
  source_files:
    - test
about:
  description: frozendict is a simple immutable dictionary. It's fast as dict, and
    sometimes faster!
  dev_url: https://github.com/Marco-Sulla/python-frozendict
  doc_url: https://github.com/Marco-Sulla/python-frozendict
  home: https://github.com/Marco-Sulla/python-frozendict
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: An immutable dictionary
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: f20fe3b4-cbdc-4f19-98ee-2c9a046f7a4b
  recipe-maintainers:
    - Marco-Sulla
    - ltalirz
  remote_url: git@github.com:AnacondaRecipes/frozendict-feedstock.git
  sha: 5db9edb14d67c968539db5bba840f7ecbd7fc5d4
