# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: libcurl
  version: 8.11.1
source:
  sha256: e9773ad1dfa21aedbfe8e1ef24c9478fa780b1b3d4f763c98dd04629b5e43485
  url: https://curl.se/download/curl-8.11.1.tar.bz2
build:
  number: 0
  run_exports:
    - libcurl >=8.11.1,<9.0a0
  string: h9bcc28a_0
requirements:
  build:
    - cctools_osx-64 949.0.1 hc7db93f_25
    - clang 14.0.6 hecd8cb5_1
    - clang-14 14.0.6 default_hd95374b_1
    - clang_osx-64 14.0.6 hb1e4b1b_0
    - clangxx 14.0.6 default_hd95374b_1
    - compiler-rt 14.0.6 hda8b6b8_0
    - compiler-rt_osx-64 14.0.6 h8d5cb93_0
    - ld64_osx-64 530 h70f3046_25
    - ldid 2.1.5 hc58f1be_3
    - libclang-cpp14 14.0.6 default_hd95374b_1
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - libllvm14 14.0.6 h26321d7_4
    - llvm-tools 14.0.6 h91fad77_4
    - tapi 1000.10.8 ha1b3eb9_0
    - zlib 1.2.13 h4b97444_1
  host:
    - c-ares 1.19.1 h6c40b1e_0
    - ca-certificates 2024.11.26 hecd8cb5_0
    - krb5 1.20.1 h428f121_1
    - libcxx 14.0.6 h9765a3e_0
    - libedit 3.1.20230828 h6c40b1e_0
    - libev 4.33 h9ed2024_1
    - libnghttp2 1.57.0 h9beae6a_0
    - libssh2 1.11.1 h3a17b82_0
    - lz4-c 1.9.4 hcec6c5f_1
    - ncurses 6.4 hcec6c5f_0
    - openssl 3.0.15 h46256e1_0
    - xz 5.4.6 h6c40b1e_1
    - zlib 1.2.13 h4b97444_1
    - zstd 1.5.2 hcb37349_0
  run:
    - krb5 >=1.20.1,<1.21.0a0
    - libnghttp2 >=1.57.0
    - libnghttp2 >=1.57.0,<2.0a0
    - libssh2 >=1.10.0
    - libssh2 >=1.11.1,<2.0a0
    - openssl >=3.0.15,<4.0a0
    - zlib >=1.2.13,<1.3.0a0
    - zstd >=1.5.2,<1.6.0a0
test:
  commands:
    - curl-config --features
    - curl-config --protocols
    - test -f ${PREFIX}/lib/libcurl${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libcurl.a
    - CURL_SSL_BACKENDS=$(curl-config --ssl-backends)
    - if ! echo $CURL_SSL_BACKENDS | grep -q "OpenSSL"; then exit 1; fi
    - if ! echo $CURL_SSL_BACKENDS | grep -q "Secure Transport"; then exit 1; fi
about:
  description: 'Curl is an open source command line tool and library for transferring
    data

    with URL syntax. It is used in command lines or scripts to transfer data.

    '
  dev_url: https://github.com/curl/curl
  doc_url: https://curl.se/docs/
  home: https://curl.se/
  license: curl
  license_family: MIT
  license_url: https://curl.se/docs/copyright.html
  summary: tool and library for transferring data with URL syntax
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: dcfa6b5d-c2b4-4ae1-87bc-793665314c36
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - xylar
  remote_url: git@github.com:AnacondaRecipes/curl-feedstock.git
  sha: 222172b88ec914c9001e3843b3f19058c422eb64
