# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_2eh84h3yiv/clone/recipe, last modified Thu Nov  7 11:05:17 2024
# ------------------------------------------------

package:
  name: requests
  version: 2.32.3
source:
  sha256: 55365417734eb18255590a9ff9eb97e9e1da868d4ccd6402399eaf68af20a760
  url: https://pypi.io/packages/source/r/requests/requests-2.32.3.tar.gz
build:
  number: '1'
  script: /var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_2eh84h3yiv/croot/requests_1730999127987/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py312hecd8cb5_1
requirements:
  host:
    - bzip2 1.0.8 h6c40b1e_6
    - ca-certificates 2024.9.24 hecd8cb5_0
    - expat 2.6.3 h6d0c2b6_0
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - ncurses 6.4 hcec6c5f_0
    - openssl 3.0.15 h46256e1_0
    - pip 24.2 py312hecd8cb5_0
    - python 3.12.7 hcd54a6c_0
    - readline 8.2 hca72f7f_0
    - setuptools 75.1.0 py312hecd8cb5_0
    - sqlite 3.45.3 h6c40b1e_0
    - tk 8.6.14 h4d00af3_0
    - tzdata 2024b h04d1e81_0
    - wheel 0.44.0 py312hecd8cb5_0
    - xz 5.4.6 h6c40b1e_1
    - zlib 1.2.13 h4b97444_1
  run:
    - certifi >=2017.4.17
    - charset-normalizer >=2,<4
    - idna >=2.5,<4
    - python >=3.12,<3.13.0a0
    - urllib3 >=1.21.1,<3
  run_constrained:
    - chardet >=3.0.2,<6
    - pysocks >=1.5.6,!=1.5.7
test:
  commands:
    - pip check
    - conda create -v --dry-run -n requests-test numpy
  imports:
    - requests
  requires:
    - conda
    - pip
about:
  description: 'Requests is the only Non-GMO HTTP library for Python, safe for human

    consumption.

    '
  dev_url: https://github.com/psf/requests
  doc_url: https://requests.readthedocs.io/
  home: https://requests.readthedocs.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "Requests is an elegant and simple HTTP library for Python, built with\
    \ \u2665."
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 2e00be24-b370-4ef5-a2e1-ea14903a87be
  recipe-maintainers:
    - carlodri
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - sigmavirus24
  remote_url: git@github.com:AnacondaRecipes/requests-feedstock.git
  sha: 997bb0da1a210a5aeef4073b32f674eaf1f8eaca
