# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_9dcqemvl4v/clone/recipe, last modified Tue Apr 30 08:23:58 2024
# ------------------------------------------------

package:
  name: jsonpatch
  version: '1.33'
source:
  sha256: 9fcd4009c41e6d12348b4a0ff2563ba56a2923a7dfee731d004e212e1ee5030c
  url: https://pypi.io/packages/source/j/jsonpatch/jsonpatch-1.33.tar.gz
build:
  number: '1'
  script: /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_9dcqemvl4v/croot/jsonpatch_1714483445583/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py312hecd8cb5_1
requirements:
  host:
    - bzip2 1.0.8 h6c40b1e_5
    - ca-certificates 2024.3.11 hecd8cb5_0
    - expat 2.6.2 hcec6c5f_0
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_0
    - ncurses 6.4 hcec6c5f_0
    - openssl 3.0.13 hca72f7f_0
    - pip 23.3.1 py312hecd8cb5_0
    - python 3.12.3 hd58486a_0
    - readline 8.2 hca72f7f_0
    - setuptools 68.2.2 py312hecd8cb5_0
    - sqlite 3.41.2 h6c40b1e_0
    - tk 8.6.12 h5d9f67b_0
    - tzdata 2024a h04d1e81_0
    - wheel 0.41.2 py312hecd8cb5_0
    - xz 5.4.6 h6c40b1e_0
    - zlib 1.2.13 h4dc903c_0
  run:
    - jsonpointer >=1.9
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
    - pytest tests.py
  imports:
    - jsonpatch
  requires:
    - pip
    - pytest
  source_files:
    - tests.*
about:
  description: 'python-json-patch is a Python library for applying JSON patches (RFC
    6902).

    Python 2.7 and 3.4+ are supported. Tests are run on both CPython and PyPy.

    '
  dev_url: https://github.com/stefankoegl/python-json-patch
  doc_url: https://python-json-patch.readthedocs.io
  home: https://github.com/stefankoegl/python-json-patch
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Apply JSON-Patches (RFC 6902)
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 9dfdc79b-519c-4d04-ab43-457808f00dd4
  recipe-maintainers:
    - anguslees
    - pavelzw
    - pmlandwehr
  remote_url: git@github.com:AnacondaRecipes/jsonpatch-feedstock.git
  sha: 65c0212085ccd2a1c3f7bb70147eacab8b594bf6
