# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_97qpgd2gkx/clone/recipe, last modified Wed Nov 20 13:32:37 2024
# ------------------------------------------------

package:
  name: cryptography
  version: 43.0.3
source:
  sha256: 315b9001266a492a6ff443b61238f956b214dbec9910a081ba5b6646a055a805
  url: https://pypi.io/packages/source/c/cryptography/cryptography-43.0.3.tar.gz
build:
  number: '1'
  script:
    - export OPENSSL_DIR=$PREFIX
    - /var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_97qpgd2gkx/croot/cryptography_1732131165709/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
      -m pip install . -vv --no-deps --no-build-isolation
  string: py312he15b966_1
requirements:
  build:
    - cctools_osx-64 949.0.1 hc7db93f_25
    - clang 14.0.6 hecd8cb5_1
    - clang-14 14.0.6 default_hd95374b_1
    - clang_osx-64 14.0.6 hb1e4b1b_0
    - clangxx 14.0.6 default_hd95374b_1
    - clangxx_osx-64 14.0.6 hd8b9576_0
    - compiler-rt 14.0.6 hda8b6b8_0
    - compiler-rt_osx-64 14.0.6 h8d5cb93_0
    - ld64_osx-64 530 h70f3046_25
    - ldid 2.1.5 hc58f1be_3
    - libclang-cpp14 14.0.6 default_hd95374b_1
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - libllvm14 14.0.6 h26321d7_4
    - llvm-tools 14.0.6 h91fad77_4
    - rust 1.82.0 he5d3d0f_0
    - rust_osx-64 1.82.0 he5d3d0f_0
    - tapi 1000.10.8 ha1b3eb9_0
    - zlib 1.2.13 h4b97444_1
  host:
    - bzip2 1.0.8 h6c40b1e_6
    - ca-certificates 2024.9.24 hecd8cb5_0
    - cffi 1.17.1 py312h9205ec4_0
    - expat 2.6.3 h6d0c2b6_0
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - maturin 1.5.1 py312h47c78ee_0
    - ncurses 6.4 hcec6c5f_0
    - openssl 3.0.15 h46256e1_0
    - pip 24.2 py312hecd8cb5_0
    - pycparser 2.21 pyhd3eb1b0_0
    - python 3.12.7 hcd54a6c_0
    - readline 8.2 hca72f7f_0
    - setuptools 72.1.0 py312hecd8cb5_0
    - sqlite 3.45.3 h6c40b1e_0
    - tk 8.6.14 h4d00af3_0
    - tzdata 2024b h04d1e81_0
    - wheel 0.44.0 py312hecd8cb5_0
    - xz 5.4.6 h6c40b1e_1
    - zlib 1.2.13 h4b97444_1
  run:
    - cffi >=1.12
    - openssl >=3.0.15,<4.0a0
    - python >=3.12,<3.13.0a0
  run_constrained:
    - __osx >=10.12
    - bcrypt >=3.1.5
test:
  commands:
    - pip check
    - pytest tests
  requires:
    - certifi
    - cryptography-vectors 43.0.3.*
    - pip
    - pretend
    - pytest >=6.2.0
    - pytest-benchmark
    - pytest-xdist
  source_files:
    - pyproject.toml
    - tests
about:
  description: 'Cryptography is a package which provides cryptographic recipes and

    primitives to Python developers. Our goal is for it to be your

    "cryptographic standard library". It supports Python 3.6+ and PyPy3 7.2+.

    cryptography includes both high level recipes and low level interfaces to

    common cryptographic algorithms such as symmetric ciphers, message digests,

    and key derivation functions.

    '
  dev_url: https://github.com/pyca/cryptography
  doc_url: https://cryptography.io/
  home: https://github.com/pyca/cryptography
  license: Apache-2.0 OR BSD-3-Clause
  license_family: OTHER
  license_file:
    - LICENSE
    - LICENSE.APACHE
    - LICENSE.BSD
  summary: Provides cryptographic recipes and primitives to Python developers
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 97ffd05a-a793-4d99-a40c-db3940e69a4e
  recipe-maintainers:
    - chenghlee
    - jakirkham
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/cryptography-feedstock.git
  sha: 7f71ebd7a05825a90011e57e561afc48ff4c61f7
