# This file created by conda-build 3.26.1
# ------------------------------------------------

package:
  name: libnghttp2
  version: 1.57.0
source:
  sha256: 1e3258453784d3b7e6cc48d0be087b168f8360b5d588c66bfeda05d07ad39ffd
  url: https://github.com/nghttp2/nghttp2/releases/download/v1.57.0/nghttp2-1.57.0.tar.gz
build:
  missing_dso_whitelist: null
  number: 0
  run_exports:
    - libnghttp2 >=1.57.0,<2.0a0
  string: h9beae6a_0
requirements:
  build:
    - cctools_osx-64 949.0.1 hc7db93f_25
    - clang 14.0.6 hecd8cb5_1
    - clang-14 14.0.6 default_hd95374b_1
    - clang_osx-64 14.0.6 hb1e4b1b_0
    - clangxx 14.0.6 default_hd95374b_1
    - clangxx_osx-64 14.0.6 hd8b9576_0
    - compiler-rt 14.0.6 hda8b6b8_0
    - compiler-rt_osx-64 14.0.6 h8d5cb93_0
    - ld64_osx-64 530 h70f3046_25
    - ldid 2.1.5 hc58f1be_3
    - libclang-cpp14 14.0.6 default_hd95374b_1
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_0
    - libllvm14 14.0.6 h91fad77_3
    - llvm-tools 14.0.6 he0576d7_3
    - make 4.2.1 h3efe00b_1
    - tapi 1000.10.8 ha1b3eb9_0
    - zlib 1.2.13 h4dc903c_0
  host:
    - c-ares 1.19.1 h6c40b1e_0
    - ca-certificates 2023.08.22 hecd8cb5_0
    - libcxx 14.0.6 h9765a3e_0
    - libev 4.33 h9ed2024_1
    - openssl 3.0.11 hca72f7f_2
    - zlib 1.2.13 h4dc903c_0
  run:
    - c-ares >=1.19.1,<2.0a0
    - c-ares >=1.7.5
    - libcxx >=14.0.6
    - libev >=4.11
    - libev >=4.33,<4.34.0a0
    - openssl >=3.0.11,<4.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - nghttp -nv https://nghttp2.org
    - test ! -f ${PREFIX}/lib/libnghttp2.a
about:
  description: 'This is an implementation of the Hypertext Transfer Protocol version
    2 in C.


    The framing layer of HTTP/2 is implemented as a reusable C library. On top

    of that, we have implemented an HTTP/2 client, server and proxy. We have

    also developed load test and benchmarking tools for HTTP/2.

    '
  dev_url: https://github.com/nghttp2/nghttp2
  doc_url: https://nghttp2.org/documentation/
  home: https://github.com/nghttp2/nghttp2
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: This is an implementation of Hypertext Transfer Protocol version 2.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: ace78513-6c9d-48b1-9013-cd295041193c
  recipe-maintainers:
    - cpaulik
    - mariusvniekerk
    - wolfv
  remote_url: git@github.com:AnacondaRecipes/nghttp2-feedstock.git
  sha: 1a799282b20250af4438083bef5673c53746bfe6
