# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_2eao3sj71x/clone/recipe, last modified Wed Dec 11 16:53:27 2024
# ------------------------------------------------

package:
  name: expat
  version: 2.6.4
source:
  sha256: 8dc480b796163d4436e6f1352e71800a774f73dbae213f1860b60607d2a83ada
  url: https://github.com/libexpat/libexpat/releases/download/R_2_6_4/expat-2.6.4.tar.bz2
build:
  number: '0'
  run_exports:
    - expat >=2.6.4,<3.0a0
  string: h6d0c2b6_0
requirements:
  build:
    - cctools_osx-64 949.0.1 hc7db93f_25
    - clang 14.0.6 hecd8cb5_1
    - clang-14 14.0.6 default_hd95374b_1
    - clang_osx-64 14.0.6 hb1e4b1b_0
    - clangxx 14.0.6 default_hd95374b_1
    - clangxx_osx-64 14.0.6 hd8b9576_0
    - compiler-rt 14.0.6 hda8b6b8_0
    - compiler-rt_osx-64 14.0.6 h8d5cb93_0
    - ld64_osx-64 530 h70f3046_25
    - ldid 2.1.5 hc58f1be_3
    - libclang-cpp14 14.0.6 default_hd95374b_1
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - libllvm14 14.0.6 h26321d7_4
    - libtool 2.4.6 hcec6c5f_1009
    - llvm-tools 14.0.6 h91fad77_4
    - make 4.2.1 h3efe00b_1
    - tapi 1000.10.8 ha1b3eb9_0
    - zlib 1.2.13 h4b97444_1
  host:
    - libcxx 14.0.6 h9765a3e_0
  run:
    - libcxx >=14.0.6
test:
  commands:
    - xmlwf -h
about:
  description: 'Expat is a stream-oriented XML parser library written in C.

    Expat excels with files too large to fit RAM, and where performance

    and flexibility are crucial.

    '
  dev_url: https://github.com/libexpat/libexpat
  doc_url: https://libexpat.github.io/doc/
  home: https://libexpat.github.io
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Expat XML parser library in C
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 2ee83020-5ed8-44da-86f1-d73db9361e2a
  recipe-maintainers:
    - kwilcox
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/expat-feedstock.git
  sha: 84120e8bef5bb45409d784d03b5b663f4e620cd4
