# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: libsolv
  version: 0.7.30
source:
  patches:
    - patches/conda_variant_priorization.patch
    - patches/no_error_subdir_mismatch.patch
    - patches/pcre2-compat.patch
  sha256: ce4aa2f0e3c5c9ab99dced6a1810af3f670f1b98892394edc68ccabe7b272133
  url: https://github.com/openSUSE/libsolv/archive/0.7.30.tar.gz
build:
  noarch: false
  noarch_python: false
  number: '1'
  script: install.sh
  string: h2761308_1
requirements:
  build:
    - bzip2 1.0.8 h6c40b1e_6
    - c-ares 1.19.1 h6c40b1e_0
    - ca-certificates 2024.11.26 hecd8cb5_0
    - cctools_osx-64 949.0.1 hc7db93f_25
    - clang 14.0.6 hecd8cb5_1
    - clang-14 14.0.6 default_hd95374b_1
    - clang_osx-64 14.0.6 hb1e4b1b_0
    - clangxx 14.0.6 default_hd95374b_1
    - clangxx_osx-64 14.0.6 hd8b9576_0
    - cmake 3.26.4 hbb7d193_0
    - compiler-rt 14.0.6 hda8b6b8_0
    - compiler-rt_osx-64 14.0.6 h8d5cb93_0
    - expat 2.6.4 h6d0c2b6_0
    - krb5 1.20.1 h428f121_1
    - ld64_osx-64 530 h70f3046_25
    - ldid 2.1.5 hc58f1be_3
    - libclang-cpp14 14.0.6 default_hd95374b_1
    - libcurl 8.9.1 h3a17b82_0
    - libcxx 14.0.6 h9765a3e_0
    - libedit 3.1.20230828 h6c40b1e_0
    - libev 4.33 h9ed2024_1
    - libffi 3.4.4 hecd8cb5_1
    - libllvm14 14.0.6 h26321d7_4
    - libmpdec 4.0.0 h46256e1_0
    - libnghttp2 1.57.0 h9beae6a_0
    - libssh2 1.11.1 h3a17b82_0
    - libuv 1.48.0 h46256e1_0
    - llvm-tools 14.0.6 h91fad77_4
    - lz4-c 1.9.4 hcec6c5f_1
    - ncurses 6.4 hcec6c5f_0
    - ninja 1.12.1 hecd8cb5_0
    - ninja-base 1.12.1 h1962661_0
    - openssl 3.0.15 h46256e1_0
    - python 3.13.1 h1ec50cd_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 hca72f7f_0
    - rhash 1.4.3 h04015c4_0
    - sqlite 3.45.3 h6c40b1e_0
    - tapi 1000.10.8 ha1b3eb9_0
    - tk 8.6.14 h4d00af3_0
    - tzdata 2024b h04d1e81_0
    - xz 5.4.6 h6c40b1e_1
    - zlib 1.2.13 h4b97444_1
    - zstd 1.5.6 h138b38a_0
  host:
    - bzip2 1.0.8 h6c40b1e_6
    - libcxx 14.0.6 h9765a3e_0
    - libiconv 1.16 h6c40b1e_3
    - pcre2 10.42 h9b97e30_1
    - pkg-config 0.29.2 h3efe00b_8
    - zlib 1.2.13 h4b97444_1
  run:
    - libcxx >=14.0.6
    - pcre2 >=10.42,<10.43.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libsolv${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libsolvext${SHLIB_EXT}
    - test -f ${PREFIX}/include/solv/repo.h
    - dumpsolv -h
about:
  description: 'libsolv, a free package dependency solver using a satisfiability algorithm.

    '
  dev_url: https://github.com/openSUSE/libsolv
  doc_url: https://github.com/openSUSE/libsolv/tree/master/doc
  home: https://github.com/openSUSE/libsolv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.BSD
  summary: Library for solving packages and reading repositories
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 28e21e69-4426-48e7-964e-b63f987e1a3c
  recipe-maintainers:
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - davidbrochart
    - wolfv
  remote_url: git@github.com:AnacondaRecipes/libsolv-feedstock.git
  sha: 20f7f0a13a1a12d7b1ef839d650dd156df024468
