# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_0953hagtqo/clone/recipe, last modified Fri Nov 29 08:38:10 2024
# ------------------------------------------------

package:
  name: libssh2
  version: 1.11.1
source:
  sha256: d9ec76cbe34db98eec3539fe2c899d26b0c837cb3eb466a56b0f109cabf658f7
  url: https://www.libssh2.org/download/libssh2-1.11.1.tar.gz
build:
  number: '0'
  run_exports:
    - libssh2 >=1.11.1,<2.0a0
  string: h3a17b82_0
requirements:
  build:
    - cctools_osx-64 949.0.1 hc7db93f_25
    - clang 14.0.6 hecd8cb5_1
    - clang-14 14.0.6 default_hd95374b_1
    - clang_osx-64 14.0.6 hb1e4b1b_0
    - clangxx 14.0.6 default_hd95374b_1
    - cmake-no-system 3.25.3 hcec6c5f_0
    - compiler-rt 14.0.6 hda8b6b8_0
    - compiler-rt_osx-64 14.0.6 h8d5cb93_0
    - ld64_osx-64 530 h70f3046_25
    - ldid 2.1.5 hc58f1be_3
    - libclang-cpp14 14.0.6 default_hd95374b_1
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - libllvm14 14.0.6 h26321d7_4
    - llvm-tools 14.0.6 h91fad77_4
    - ninja-base 1.12.1 h1962661_0
    - tapi 1000.10.8 ha1b3eb9_0
    - zlib 1.2.13 h4b97444_1
  host:
    - ca-certificates 2024.11.26 hecd8cb5_0
    - openssl 3.0.15 h46256e1_0
    - zlib 1.2.13 h4b97444_1
  run:
    - openssl >=3.0.15,<4.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f $PREFIX/include/libssh2.h
    - test -f $PREFIX/include/libssh2_publickey.h
    - test -f $PREFIX/include/libssh2_sftp.h
    - test -f $PREFIX/lib/libssh2${SHLIB_EXT}
    - test -f $PREFIX/lib/pkgconfig/libssh2.pc
about:
  description: 'libssh2 is a library implementing the SSH2 protocol, available under
    the revised BSD license.

    '
  dev_url: https://github.com/libssh2/libssh2
  doc_url: https://www.libssh2.org/docs.html
  home: https://www.libssh2.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: the SSH library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 09c65419-610d-4513-a9c7-7c561e306ffb
  recipe-maintainers:
    - shadowwalkersb
  remote_url: git@github.com:AnacondaRecipes/libssh2-feedstock.git
  sha: ccf17c18a57eafac668302e8b68bd89ce4526611
