# This file created by conda-build 3.26.0
# ------------------------------------------------

package:
  name: c-ares
  version: 1.19.1
source:
  sha256: 321700399b72ed0e037d0074c629e7741f6b2ec2dda92956abe3e9671d3e268e
  url: https://c-ares.org/download/c-ares-1.19.1.tar.gz
build:
  number: 0
  run_exports:
    - c-ares >=1.19.1,<2.0a0
  string: h6c40b1e_0
requirements:
  build:
    - bzip2 1.0.8 h1de35cc_0
    - ca-certificates 2023.05.30 hecd8cb5_0
    - cctools_osx-64 949.0.1 hc7db93f_25
    - clang 14.0.6 hecd8cb5_1
    - clang-14 14.0.6 default_hd95374b_1
    - clang_osx-64 14.0.6 hb1e4b1b_0
    - clangxx 14.0.6 default_hd95374b_1
    - cmake-no-system 3.25.3 hcec6c5f_0
    - compiler-rt 14.0.6 hda8b6b8_0
    - compiler-rt_osx-64 14.0.6 h8d5cb93_0
    - ld64_osx-64 530 h70f3046_25
    - ldid 2.1.5 hc58f1be_3
    - libclang-cpp14 14.0.6 default_hd95374b_1
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_0
    - libllvm14 14.0.6 h91fad77_3
    - llvm-tools 14.0.6 he0576d7_3
    - ncurses 6.4 hcec6c5f_0
    - ninja 1.10.2 hecd8cb5_5
    - ninja-base 1.10.2 haf03e11_5
    - openssl 3.0.10 hca72f7f_2
    - python 3.11.4 hf27a42d_0
    - readline 8.2 hca72f7f_0
    - sqlite 3.41.2 h6c40b1e_0
    - tapi 1000.10.8 ha1b3eb9_0
    - tk 8.6.12 h5d9f67b_0
    - tzdata 2023c h04d1e81_0
    - xz 5.4.2 h6c40b1e_0
    - zlib 1.2.13 h4dc903c_0
  run: []
  run_constraint:
    - c-ares-static <0a0
test:
  commands:
    - test -f ${PREFIX}/include/ares.h
    - test -f ${PREFIX}/lib/libcares${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libcares.a
    - test ! -f ${PREFIX}/lib/libcares_static.a
about:
  description: 'c-ares is a C library for asynchronous DNS requests (including name
    resolves).

    '
  dev_url: https://github.com/c-ares/c-ares
  doc_url: https://c-ares.org/docs.html
  home: https://c-ares.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: This is c-ares, an asynchronous resolver library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 27f7e3a0-60de-477f-819f-086588a101f8
  recipe-maintainers:
    - ocefpaf
    - wesm
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/c-ares-feedstock.git
  sha: ad2761d18574c8f2dbc14f4e4c3c82bd5fe1d62a
