# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_9525zen30f/clone/recipe, last modified Tue Apr 30 16:18:17 2024
# ------------------------------------------------

package:
  name: xz
  version: 5.4.6
source:
  sha256: 913851b274e8e1d31781ec949f1c23e8dbcf0ecf6e73a2436dc21769dd3e6f49
  url: https://github.com/tukaani-project/xz/releases/download/v5.4.6/xz-5.4.6.tar.bz2
build:
  number: '1'
  run_exports:
    - xz >=5.4.6,<6.0a0
  string: h6c40b1e_1
requirements:
  build:
    - autoconf 2.71 pl5340h6c40b1e_0
    - automake 1.16.5 pl5340hecd8cb5_1
    - cctools_osx-64 949.0.1 hc7db93f_25
    - clang 14.0.6 hecd8cb5_1
    - clang-14 14.0.6 default_hd95374b_1
    - clang_osx-64 14.0.6 hb1e4b1b_0
    - clangxx 14.0.6 default_hd95374b_1
    - compiler-rt 14.0.6 hda8b6b8_0
    - compiler-rt_osx-64 14.0.6 h8d5cb93_0
    - gdbm 1.18 hdccc71a_4
    - ld64_osx-64 530 h70f3046_25
    - ldid 2.1.5 hc58f1be_3
    - libclang-cpp14 14.0.6 default_hd95374b_1
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - libllvm14 14.0.6 h91fad77_3
    - libtool 2.4.6 hcec6c5f_1009
    - llvm-tools 14.0.6 he0576d7_3
    - m4 1.4.18 h1de35cc_1
    - make 4.2.1 h3efe00b_1
    - ncurses 6.4 hcec6c5f_0
    - perl 5.34.0 h435f0c2_2
    - readline 8.2 hca72f7f_0
    - tapi 1000.10.8 ha1b3eb9_0
    - zlib 1.2.13 h4dc903c_0
  host: []
  run: []
test:
  commands:
    - xz --help
    - unxz --help
    - lzma --help
    - test -f ${PREFIX}/include/lzma.h
    - test -f ${PREFIX}/lib/pkgconfig/liblzma.pc
    - test -f `pkg-config --variable=libdir --dont-define-prefix liblzma`/liblzma${SHLIB_EXT}
    - test -f ${PREFIX}/lib/liblzma.a
    - test -f ${PREFIX}/lib/liblzma${SHLIB_EXT}
    - test -f ${PREFIX}/lib/liblzma.5${SHLIB_EXT}
    - conda inspect linkages -p $PREFIX $PKG_NAME
    - conda inspect objects -p $PREFIX $PKG_NAME
  requires:
    - conda-build
    - pkg-config
about:
  description: 'XZ Utils is free general-purpose data compression software with a
    high

    compression ratio. XZ Utils were written for POSIX-like systems, but also

    work on some not-so-POSIX systems.

    '
  dev_url: https://github.com/tukaani-project/xz
  doc_url: https://tukaani.org/xz/
  home: https://xz.tukaani.org/xz-utils/
  license: LGPL-2.1-or-later and GPL-2.0-or-later and 0BSD
  license_family: GPL2
  license_file: COPYING
  summary: Data compression software with high compression ratio
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 95bc7a88-8aa6-4524-be67-c2e77e557928
  recipe-maintainers:
    - mingwandroid
    - msarahan
    - nehaljwani
    - ocefpaf
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/xz-feedstock.git
  sha: e4727181dd6dd975f850faa66a9233fd6773eac8
