# This file created by conda-build 3.26.0
# meta.yaml template originally from:
# /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_09mis60fnk/clone/recipe, last modified Thu Aug 17 12:23:59 2023
# ------------------------------------------------

package:
  name: icu
  version: '73.1'
source:
  - patches:
      - icu-22356.patch
      - mach-port-t.patch
    sha256: a457431de164b4aa7eca00ed134d00dfbf88a77c6986a10ae7774fc076bb8c45
    url: https://github.com/unicode-org/icu/releases/download/release-73-1/icu4c-73_1-src.tgz
  - folder: source/data
    sha256: 07d7557efb30fc2e9b74652f1525603b3209a4539d2d345d704e3df3bf9b957e
    url: https://github.com/unicode-org/icu/releases/download/release-73-1/icu4c-73_1-data.zip
build:
  number: '0'
  run_exports:
    - icu >=73.1,<74.0a0
  string: hcec6c5f_0
requirements:
  build:
    - cctools_osx-64 949.0.1 hc7db93f_25
    - clang 14.0.6 hecd8cb5_1
    - clang-14 14.0.6 default_hd95374b_1
    - clang_osx-64 14.0.6 hb1e4b1b_0
    - clangxx 14.0.6 default_hd95374b_1
    - clangxx_osx-64 14.0.6 hd8b9576_0
    - compiler-rt 14.0.6 hda8b6b8_0
    - compiler-rt_osx-64 14.0.6 h8d5cb93_0
    - ld64_osx-64 530 h70f3046_25
    - ldid 2.1.5 hc58f1be_3
    - libclang-cpp14 14.0.6 default_hd95374b_1
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_0
    - libllvm14 14.0.6 h91fad77_3
    - libtool 2.4.6 hcec6c5f_1009
    - llvm-tools 14.0.6 he0576d7_3
    - make 4.2.1 h3efe00b_1
    - patch 2.7.6 h1de35cc_1001
    - tapi 1000.10.8 ha1b3eb9_0
    - zlib 1.2.13 h4dc903c_0
  host:
    - libcxx 14.0.6 h9765a3e_0
  run:
    - libcxx >=14.0.6
test:
  commands:
    - test -f $PREFIX/lib/libicudata.a
    - test -f $PREFIX/lib/libicudata.73.1.dylib
    - test -f $PREFIX/lib/libicui18n.a
    - test -f $PREFIX/lib/libicui18n.73.1.dylib
    - test -f $PREFIX/lib/libicuio.a
    - test -f $PREFIX/lib/libicuio.73.1.dylib
    - test -f $PREFIX/lib/libicutest.a
    - test -f $PREFIX/lib/libicutest.73.1.dylib
    - test -f $PREFIX/lib/libicutu.a
    - test -f $PREFIX/lib/libicutu.73.1.dylib
    - test -f $PREFIX/lib/libicuuc.a
    - test -f $PREFIX/lib/libicuuc.73.1.dylib
    - genbrk --help
    - gencfu --help
    - gencnval --help
    - gendict --help
    - icuinfo --help
    - icu-config --help
    - makeconv gb-18030-2000.ucm
    - genrb de.txt
    - echo "de.res" > list.txt
    - pkgdata -p mybundle list.txt
  files:
    - de.txt
    - gb-18030-2000.ucm
about:
  description: 'ICU is a mature, widely used set of C/C++ and Java libraries providing

    Unicode and Globalization support for software applications. ICU is

    widely portable and gives applications the same results on all platforms

    and between C/C++ and Java software.

    '
  dev_url: https://github.com/unicode-org/icu
  doc_url: https://unicode-org.github.io/icu/
  home: https://icu.unicode.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: International Components for Unicode.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 0932b6cb-1c20-4161-bfe7-a5cce7f7de01
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - msarahan
    - ocefpaf
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/icu-feedstock.git
  sha: be820b07c5e0bff9e01e173920897db1b55e815a
