# This file created by conda-build 24.1.2
# ------------------------------------------------

package:
  name: reproc-cpp
  version: 14.2.4
source:
  - patches:
      - apple_gettime.patch
    sha256: 55c780f7faa5c8cabd83ebbb84b68e5e0e09732de70a129f6b3c801e905415dd
    url: https://github.com/DaanDeMeyer/reproc/archive/v14.2.4.tar.gz
build:
  number: 2
  run_exports:
    - reproc-cpp >=14.2,<15.0a0
  string: hcec6c5f_2
requirements:
  build:
    - bzip2 1.0.8 h6c40b1e_6
    - c-ares 1.19.1 h6c40b1e_0
    - ca-certificates 2024.3.11 hecd8cb5_0
    - cctools_osx-64 949.0.1 hc7db93f_25
    - clang 14.0.6 hecd8cb5_1
    - clang-14 14.0.6 default_hd95374b_1
    - clang_osx-64 14.0.6 hb1e4b1b_0
    - clangxx 14.0.6 default_hd95374b_1
    - clangxx_osx-64 14.0.6 hd8b9576_0
    - cmake 3.26.4 hbb7d193_0
    - compiler-rt 14.0.6 hda8b6b8_0
    - compiler-rt_osx-64 14.0.6 h8d5cb93_0
    - expat 2.6.2 hcec6c5f_0
    - krb5 1.20.1 h428f121_1
    - ld64_osx-64 530 h70f3046_25
    - ldid 2.1.5 hc58f1be_3
    - libclang-cpp14 14.0.6 default_hd95374b_1
    - libcurl 8.5.0 hf20ceda_0
    - libcxx 14.0.6 h9765a3e_0
    - libedit 3.1.20230828 h6c40b1e_0
    - libev 4.33 h9ed2024_1
    - libffi 3.4.4 hecd8cb5_1
    - libllvm14 14.0.6 h91fad77_3
    - libnghttp2 1.57.0 h9beae6a_0
    - libssh2 1.10.0 h04015c4_3
    - libuv 1.44.2 h6c40b1e_0
    - llvm-tools 14.0.6 he0576d7_3
    - lz4-c 1.9.4 hcec6c5f_1
    - ncurses 6.4 hcec6c5f_0
    - ninja 1.10.2 hecd8cb5_5
    - ninja-base 1.10.2 haf03e11_5
    - openssl 3.0.13 hca72f7f_1
    - python 3.12.3 hd58486a_0
    - readline 8.2 hca72f7f_0
    - rhash 1.4.3 h04015c4_0
    - sqlite 3.45.3 h6c40b1e_0
    - tapi 1000.10.8 ha1b3eb9_0
    - tk 8.6.12 h5d9f67b_0
    - tzdata 2024a h04d1e81_0
    - xz 5.4.6 h6c40b1e_1
    - zlib 1.2.13 h4b97444_1
    - zstd 1.5.5 hc035e20_1
  host:
    - libcxx 14.0.6 h9765a3e_0
    - reproc 14.2.4 hcec6c5f_2
  run:
    - libcxx >=14.0.6
    - reproc 14.2.4 hcec6c5f_2
test:
  commands:
    - test -f ${PREFIX}/include/reproc++/reproc.hpp
    - test -f ${PREFIX}/lib/libreproc++${SHLIB_EXT}
    - test -f ${PREFIX}/lib/cmake/reproc++/reproc++-config.cmake
    - test ! -f ${PREFIX}/lib/libreproc++.a
about:
  dev_url: https://github.com/DaanDeMeyer/reproc
  doc_src_url: https://github.com/DaanDeMeyer/reproc
  doc_url: https://github.com/DaanDeMeyer/reproc#reproc
  home: https://github.com/DaanDeMeyer/reproc
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: reproc (Redirected Process) is a cross-platform C/C++ library that simplifies
    starting, stopping and communicating with external programs.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 65ee9584-eba1-45f4-b9d7-a4f3a9616cbd
  recipe-maintainers:
    - DaanDeMeyer
    - wolfv
  remote_url: git@github.com:AnacondaRecipes/reproc-feedstock.git
  sha: 39002db99a2955d830945b69264da997a7bf10aa
