# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_67p9tvgx9q/clone/recipe, last modified Tue Jan 14 09:31:47 2025
# ------------------------------------------------

package:
  name: pycosat
  version: 0.6.6
source:
  patches:
    - patches/0001-GH-100-Replace-unittest.makeSuite-with-unittest.defaultTest.patch
  sha256: b0014986321e77a36d8fe24827698aae076500c817133a700608bd677b77a998
  url: https://github.com/conda/pycosat/archive/0.6.6.tar.gz
build:
  number: '2'
  script: /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_67p9tvgx9q/croot/pycosat_1736868714508/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . --no-deps -vv --no-build-isolation
  string: py312h46256e1_2
requirements:
  build:
    - cctools_osx-64 949.0.1 hc7db93f_25
    - clang 14.0.6 hecd8cb5_2
    - clang-14 14.0.6 default_h182e8cd_2
    - clang_osx-64 14.0.6 hb1e4b1b_0
    - clangxx 14.0.6 default_h182e8cd_2
    - compiler-rt 14.0.6 hda8b6b8_0
    - compiler-rt_osx-64 14.0.6 h8d5cb93_0
    - ld64_osx-64 530 h70f3046_25
    - ldid 2.1.5 hc58f1be_3
    - libclang-cpp14 14.0.6 default_h182e8cd_2
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - libllvm14 14.0.6 h26321d7_4
    - llvm-tools 14.0.6 h91fad77_4
    - patch 2.7.6 h1de35cc_1001
    - tapi 1000.10.8 ha1b3eb9_0
    - zlib 1.2.13 h4b97444_1
  host:
    - bzip2 1.0.8 h6c40b1e_6
    - ca-certificates 2024.12.31 hecd8cb5_0
    - expat 2.6.4 h6d0c2b6_0
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - ncurses 6.4 hcec6c5f_0
    - openssl 3.0.15 h46256e1_0
    - pip 24.2 py312hecd8cb5_0
    - python 3.12.8 hcd54a6c_0
    - readline 8.2 hca72f7f_0
    - setuptools 75.1.0 py312hecd8cb5_0
    - sqlite 3.45.3 h6c40b1e_0
    - tk 8.6.14 h4d00af3_0
    - tzdata 2024b h04d1e81_0
    - wheel 0.44.0 py312hecd8cb5_0
    - xz 5.4.6 h6c40b1e_1
    - zlib 1.2.13 h4b97444_1
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
    - python test_package.py "0.6.6"
  files:
    - qg3-08.cnf
    - sudoku.py
    - test_package.py
    - uf20-098.cnf
  imports:
    - pycosat
  requires:
    - pip
about:
  description: 'PicoSAT is a popular SAT solver written by Armin Biere in pure C.
    This

    package provides efficient Python bindings to picosat on the C level, i.e.

    when importing pycosat, the picosat solver becomes part of the Python

    process itself.

    '
  dev_url: https://github.com/conda/pycosat
  doc_url: https://github.com/conda/pycosat/blob/master/README.rst
  home: https://github.com/conda/pycosat
  license: MIT
  license_family: MIT
  license_url: https://github.com/conda/pycosat/blob/0.6.6/LICENSE
  summary: Bindings to picosat (a SAT solver)
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 67e0206e-f2e4-4012-96f0-1d52fd6902c5
  recipe-maintainers:
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - nehaljwani
    - pelson
  remote_url: git@github.com:AnacondaRecipes/pycosat-feedstock.git
  sha: 3b293122c88ae0e420700408e363b20fb0b58a35
