# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: brotli-python
  version: 1.0.9
source:
  fn: brotli-1.0.9.tar.gz
  patches:
    - 0001-Add-separate-options-to-disable-shared-static-librar.patch
    - 0002-Fix-pkgconfig-rpath.patch
  sha256: f9e8d81d0405ba66d181529af42a3354f838c939095ff99930da6aa9cdf6fe46
  url: https://github.com/google/brotli/archive/v1.0.9.tar.gz
build:
  number: 9
  run_exports:
    - brotli >=1.0.9,<2.0a0
  string: py312h6d0c2b6_9
requirements:
  build:
    - bzip2 1.0.8 h6c40b1e_6
    - c-ares 1.19.1 h6c40b1e_0
    - ca-certificates 2024.11.26 hecd8cb5_0
    - cctools_osx-64 949.0.1 hc7db93f_25
    - clang 14.0.6 hecd8cb5_2
    - clang-14 14.0.6 default_h182e8cd_2
    - clang_osx-64 14.0.6 hb1e4b1b_0
    - clangxx 14.0.6 default_h182e8cd_2
    - clangxx_osx-64 14.0.6 hd8b9576_0
    - cmake 3.31.2 hc67f837_0
    - compiler-rt 14.0.6 hda8b6b8_0
    - compiler-rt_osx-64 14.0.6 h8d5cb93_0
    - expat 2.6.4 h6d0c2b6_0
    - krb5 1.20.1 h428f121_1
    - ld64_osx-64 530 h70f3046_25
    - ldid 2.1.5 hc58f1be_3
    - libclang-cpp14 14.0.6 default_h182e8cd_2
    - libcurl 8.11.1 h9bcc28a_0
    - libcxx 14.0.6 h9765a3e_0
    - libedit 3.1.20230828 h6c40b1e_0
    - libev 4.33 h9ed2024_1
    - libffi 3.4.4 hecd8cb5_1
    - libllvm14 14.0.6 h26321d7_4
    - libmpdec 4.0.0 h46256e1_0
    - libnghttp2 1.57.0 h9beae6a_0
    - libssh2 1.11.1 h3a17b82_0
    - libuv 1.48.0 h46256e1_0
    - llvm-tools 14.0.6 h91fad77_4
    - lz4-c 1.9.4 hcec6c5f_1
    - ncurses 6.4 hcec6c5f_0
    - ninja 1.12.1 hecd8cb5_0
    - ninja-base 1.12.1 h1962661_0
    - openssl 3.0.15 h46256e1_0
    - python 3.13.1 h1ec50cd_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 hca72f7f_0
    - rhash 1.4.3 h04015c4_0
    - sqlite 3.45.3 h6c40b1e_0
    - tapi 1000.10.8 ha1b3eb9_0
    - tk 8.6.14 h4d00af3_0
    - tzdata 2024b h04d1e81_0
    - xz 5.4.6 h6c40b1e_1
    - zlib 1.2.13 h4b97444_1
    - zstd 1.5.6 h138b38a_0
  host:
    - brotli 1.0.9 h46256e1_9
    - bzip2 1.0.8 h6c40b1e_6
    - ca-certificates 2024.11.26 hecd8cb5_0
    - expat 2.6.4 h6d0c2b6_0
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - ncurses 6.4 hcec6c5f_0
    - openssl 3.0.15 h46256e1_0
    - pip 24.2 py312hecd8cb5_0
    - python 3.12.8 hcd54a6c_0
    - readline 8.2 hca72f7f_0
    - setuptools 75.1.0 py312hecd8cb5_0
    - sqlite 3.45.3 h6c40b1e_0
    - tk 8.6.14 h4d00af3_0
    - tzdata 2024b h04d1e81_0
    - wheel 0.44.0 py312hecd8cb5_0
    - xz 5.4.6 h6c40b1e_1
    - zlib 1.2.13 h4b97444_1
  run:
    - libcxx >=14.0.6
    - python >=3.12,<3.13.0a0
test:
  imports:
    - brotli
about:
  home: https://github.com/google/brotli
  license: MIT
  license_file: LICENSE
  summary: Brotli compression format
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: d7986629-314c-4b82-a364-b99fb0aa7424
  recipe-maintainers:
    - CJ-Wright
    - wesm
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/brotli-feedstock.git
  sha: e0260ee00c16a7a91d596a06c9f3c405c1b53335
