# This file created by conda-build 24.5.0
# meta.yaml template originally from:
# /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_79eiw13go3/clone/recipe, last modified Fri Aug 30 08:07:46 2024
# ------------------------------------------------

package:
  name: python.app
  version: '3'
build:
  number: '1'
  string: py312h46256e1_1
requirements:
  build:
    - cctools_osx-64 949.0.1 hc7db93f_25
    - clang 14.0.6 hecd8cb5_1
    - clang-14 14.0.6 default_hd95374b_1
    - clang_osx-64 14.0.6 hb1e4b1b_0
    - clangxx 14.0.6 default_hd95374b_1
    - compiler-rt 14.0.6 hda8b6b8_0
    - compiler-rt_osx-64 14.0.6 h8d5cb93_0
    - ld64_osx-64 530 h70f3046_25
    - ldid 2.1.5 hc58f1be_3
    - libclang-cpp14 14.0.6 default_hd95374b_1
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - libllvm14 14.0.6 h91fad77_3
    - llvm-tools 14.0.6 he0576d7_3
    - tapi 1000.10.8 ha1b3eb9_0
    - zlib 1.2.13 h4b97444_1
  host:
    - bzip2 1.0.8 h6c40b1e_6
    - ca-certificates 2024.7.2 hecd8cb5_0
    - expat 2.6.2 hcec6c5f_0
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - ncurses 6.4 hcec6c5f_0
    - openssl 3.0.14 h46256e1_0
    - python 3.12.4 hcd54a6c_1
    - readline 8.2 hca72f7f_0
    - sqlite 3.45.3 h6c40b1e_0
    - tk 8.6.14 h4d00af3_0
    - tzdata 2024a h04d1e81_0
    - xz 5.4.6 h6c40b1e_1
    - zlib 1.2.13 h4b97444_1
  run:
    - python >=3.12,<3.13.0a0
test:
  files:
    - t.py
about:
  home: https://www.python.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Proxy on macOS letting Python libraries hook into the GUI event loop
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 79f45409-7b13-45e8-ab18-0db7aa2809ba
  recipe-maintainers:
    - ChrisBarker-NOAA
    - cpbotha
    - hoechenberger
  remote_url: git@github.com:AnacondaRecipes/python.app-feedstock.git
  sha: 87283f59838171f8b58241b0750e8af133e1606c
