# This file created by conda-build 24.5.1
# ------------------------------------------------

package:
  name: python
  version: 3.12.9
source:
  - patches:
      - patches/0000-branding.patch
      - patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - patches/0002-Win32-Do-not-download-externals.patch
      - patches/0003-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0004-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
      - patches/0005-Unvendor-openssl.patch
      - patches/0006-Unvendor-sqlite3.patch
      - patches/0007-Add-CondaEcosystemModifyDllSearchPath.patch
      - patches/0008-Doing-d1trimfile.patch
      - patches/0009-cross-compile-darwin.patch
      - patches/0010-Fix-TZPATH-on-windows.patch
      - patches/0011-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
      - patches/0012-Unvendor-bzip2.patch
      - patches/0013-Unvendor-libffi.patch
      - patches/0014-Unvendor-tcltk.patch
      - patches/0015-unvendor-xz.patch
      - patches/0016-unvendor-zlib.patch
      - patches/0017-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
      - patches/0018-Unvendor-expat.patch
      - patches/0019-Remove-unused-readelf.patch
      - patches/0021-Override-configure-LIBFFI.patch
    sha256: 7220835d9f90b37c006e9842a8dff4580aaca4318674f947302b8d28f3f81112
    url: https://www.python.org/ftp/python/3.12.9/Python-3.12.9.tar.xz
build:
  activate_in_script: true
  detect_binary_files_with_prefix: true
  ignore_run_exports_from:
    - clangxx_osx-64 14.*
  no_link: null
  number: 0
  script_env:
    - CONDA_FORGE=no
    - PY_INTERP_DEBUG=no
    - PY_INTERP_LINKAGE_NATURE=static
  string: hcd54a6c_0
requirements:
  build:
    - cctools_osx-64 949.0.1 hc7db93f_25
    - clang 14.0.6 hecd8cb5_2
    - clang-14 14.0.6 default_h182e8cd_2
    - clang_osx-64 14.0.6 hb1e4b1b_0
    - clangxx 14.0.6 default_h182e8cd_2
    - clangxx_osx-64 14.0.6 hd8b9576_0
    - compiler-rt 14.0.6 hda8b6b8_0
    - compiler-rt_osx-64 14.0.6 h8d5cb93_0
    - gettext 0.21.0 h4e8c18a_2
    - icu 73.1 hcec6c5f_0
    - ld64_osx-64 530 h70f3046_25
    - ldid 2.1.5 hc58f1be_3
    - libclang-cpp14 14.0.6 default_h182e8cd_2
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - libiconv 1.16 h6c40b1e_3
    - libllvm14 14.0.6 h26321d7_4
    - libtool 2.4.7 h6d0c2b6_0
    - libxml2 2.13.5 h6070cd6_0
    - llvm-openmp 14.0.6 h0dcd299_0
    - llvm-tools 14.0.6 h91fad77_4
    - make 4.2.1 h3efe00b_1
    - ncurses 6.4 hcec6c5f_0
    - pkg-config 0.29.2 h3efe00b_8
    - sed 4.8 haf1e3a3_0
    - tapi 1000.10.8 ha1b3eb9_0
    - xz 5.4.6 h6c40b1e_1
    - zlib 1.2.13 h4b97444_1
  host:
    - bzip2 1.0.8 h6c40b1e_6
    - ca-certificates 2024.12.31 hecd8cb5_0
    - expat 2.6.4 h6d0c2b6_0
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - ncurses 6.4 hcec6c5f_0
    - openssl 3.0.15 h46256e1_0
    - readline 8.1.2 hca72f7f_1
    - sqlite 3.45.3 h6c40b1e_0
    - tk 8.6.14 h4d00af3_0
    - xz 5.4.6 h6c40b1e_1
    - zlib 1.2.13 h4b97444_1
  run:
    - bzip2 >=1.0.8,<2.0a0
    - expat >=2.6.4,<3.0a0
    - libffi >=3.4,<4.0a0
    - ncurses >=6.4,<7.0a0
    - openssl >=3.0.15,<4.0a0
    - readline >=8.1.2,<9.0a0
    - sqlite >=3.45.3,<4.0a0
    - tk >=8.6.14,<8.7.0a0
    - tzdata
    - xz >=5.4.6,<6.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - python -V
    - python3 -V
    - 2to3 -h
    - pydoc -h
    - python3-config --help
    - python -c "from zoneinfo import ZoneInfo; from datetime import datetime; dt
      = datetime(2020, 10, 31, 12, tzinfo=ZoneInfo('America/Los_Angeles')); print(dt.tzname())"
    - python -m venv test-venv
    - test-venv/bin/python -c "import ctypes"
    - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    - for f in ${CONDA_PREFIX}/lib/python*/_sysconfig*.py; do echo "Checking $f:";
      if [[ `rg @[^@]*@ $f` ]]; then echo "FAILED ON $f"; cat $f; exit 1; fi; done
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.a
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.nolto.a
    - pushd tests
    - pushd prefix-replacement
    - bash build-and-test.sh
    - popd
    - pushd cmake
    - cmake -GNinja -DPY_VER=3.12.9
    - popd
    - popd
    - python run_test.py
    - test ! -f default.profraw
    - test -d "$PREFIX/lib/python3.1/site-packages"
    - python3.1 --version
    - python -c "from ctypes import CFUNCTYPE; CFUNCTYPE(None)(id)"
  files:
    - run_test.py
    - tests/cmake/*
    - tests/cython/*
    - tests/prefix-replacement/*
  requires:
    - clang_osx-64 14.*
    - clangxx_osx-64 14.*
    - cmake-no-system
    - make
    - ninja-base
    - ripgrep
about:
  description: 'Python is a widely used high-level, general-purpose, interpreted,
    dynamic

    programming language. Its design philosophy emphasizes code

    readability, and its syntax allows programmers to express concepts in

    fewer lines of code than would be possible in languages such as C++ or

    Java. The language provides constructs intended to enable clear programs

    on both a small and large scale.

    '
  dev_url: https://devguide.python.org/
  doc_url: https://www.python.org/doc/versions/
  home: https://www.python.org/
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  license_url: https://docs.python.org/3/license.html
  summary: General purpose programming language
extra:
  copy_test_source_files: true
  feedstock-name: python
  final: true
  flow_run_id: e0b55764-d179-4cd8-8a7c-90315af86d5a
  recipe-maintainers:
    - isuruf
    - jakirkham
    - katietz
    - mbargull
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/python-feedstock.git
  sha: d305561abddccab5548e233aa0bae8e0b233a346
  skip-lints:
    - license_file_overspecified
