# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_9abq1vdv2c/clone/recipe, last modified Wed Nov 27 12:33:54 2024
# ------------------------------------------------

package:
  name: anaconda-anon-usage
  version: 0.5.0
source:
  sha256: 549abbf34472dbdf332009f95e4b1278d7b0d839085a8b95eb6b73e4b3b42b80
  url: https://github.com/anaconda/anaconda-anon-usage/archive/refs/tags/0.5.0.tar.gz
build:
  number: '100'
  script_env:
    - NEED_SCRIPTS=no
  string: py312hfb7c958_100
requirements:
  host:
    - bzip2 1.0.8 h6c40b1e_6
    - ca-certificates 2024.9.24 hecd8cb5_0
    - expat 2.6.3 h6d0c2b6_0
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - ncurses 6.4 hcec6c5f_0
    - openssl 3.0.15 h46256e1_0
    - pip 24.2 py312hecd8cb5_0
    - python 3.12.7 hcd54a6c_0
    - readline 8.2 hca72f7f_0
    - setuptools 75.1.0 py312hecd8cb5_0
    - sqlite 3.45.3 h6c40b1e_0
    - tk 8.6.14 h4d00af3_0
    - tzdata 2024b h04d1e81_0
    - wheel 0.44.0 py312hecd8cb5_0
    - xz 5.4.6 h6c40b1e_1
    - zlib 1.2.13 h4b97444_1
  run:
    - python >=3.12,<3.13.0a0
  run_constrained:
    - conda >=23.7
test:
  commands:
    - export ANACONDA_ANON_USAGE_DEBUG=1
    - export PYTHONUNBUFFERED=1
    - conda create -n testchild1 --yes
    - conda create -n testchild2 --yes
    - conda info
    - conda info --envs
    - pytest -v tests/unit
    - python tests/integration/test_config.py
  imports:
    - anaconda_anon_usage
  requires:
    - conda >=23.7
    - pytest
    - pytest-cov
  source_files:
    - tests
about:
  description: 'This package augments the request header data that conda delivers

    to package servers during index and package requests. Specifically,

    three randomly generated tokens are appended to the "user agent"

    that Conda already sends with each request.

    '
  dev_url: https://github.com/anaconda/anaconda-anon-usage/
  doc_url: https://github.com/anaconda/anaconda-anon-usage/
  home: https://github.com/anaconda/anaconda-anon-usage
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: basic anonymous telemetry for conda clients
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 9a038461-d22c-411e-affa-4a50bfcc87da
  remote_url: git@github.com:AnacondaRecipes/anaconda-anon-usage-feedstock.git
  sha: e0c8b8fec0176f8dd295c0a992ab60928b41b80f
