# This file created by conda-build 24.5.0
# meta.yaml template originally from:
# /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_7686w6nsvt/clone/recipe, last modified Thu Sep  5 09:09:05 2024
# ------------------------------------------------

package:
  name: openssl
  version: 3.0.15
source:
  sha256: 23c666d0edf20f14249b3d8f0368acaee9ab585b09e1de82107c66e1f3ec9533
  url: https://github.com/openssl/openssl/releases/download/openssl-3.0.15/openssl-3.0.15.tar.gz
build:
  binary_has_prefix_files:
    - lib/libcrypto.3.0.dylib
    - lib/libcrypto.a
  detect_binary_files_with_prefix: true
  has_prefix_files:
    - bin/c_rehash
    - lib/pkgconfig/libcrypto.pc
    - lib/pkgconfig/libssl.pc
    - lib/pkgconfig/openssl.pc
  no_link: lib/libcrypto.3.0.dylib
  number: '0'
  run_exports:
    - openssl >=3.0.15,<4.0a0
  string: h46256e1_0
requirements:
  build:
    - cctools_osx-64 949.0.1 hc7db93f_25
    - clang 14.0.6 hecd8cb5_1
    - clang-14 14.0.6 default_hd95374b_1
    - clang_osx-64 14.0.6 hb1e4b1b_0
    - clangxx 14.0.6 default_hd95374b_1
    - compiler-rt 14.0.6 hda8b6b8_0
    - compiler-rt_osx-64 14.0.6 h8d5cb93_0
    - gdbm 1.18 hdccc71a_4
    - ld64_osx-64 530 h70f3046_25
    - ldid 2.1.5 hc58f1be_3
    - libclang-cpp14 14.0.6 default_hd95374b_1
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - libllvm14 14.0.6 h91fad77_3
    - llvm-tools 14.0.6 he0576d7_3
    - make 4.2.1 h3efe00b_1
    - ncurses 6.4 hcec6c5f_0
    - perl 5.34.0 h435f0c2_2
    - readline 8.2 hca72f7f_0
    - tapi 1000.10.8 ha1b3eb9_0
    - zlib 1.2.13 h4b97444_1
  run:
    - ca-certificates
test:
  commands:
    - touch checksum.txt
    - openssl sha256 checksum.txt
    - openssl ecparam -name prime256v1
    - python -c "import urllib.request; urllib.request.urlopen('https://pypi.org')"
    - pkg-config --print-errors --exact-version "3.0.15" openssl
  requires:
    - pkg-config
    - python 3.8.*
about:
  description: 'OpenSSL is a robust, commercial-grade, full-featured Open Source Toolkit

    for the Transport Layer Security (TLS) protocol formerly known as the

    Secure Sockets Layer (SSL) protocol. The protocol implementation is based

    on a full-strength general purpose cryptographic library, which can also

    be used stand-alone.

    '
  dev_url: https://github.com/openssl/openssl
  doc_url: https://www.openssl.org/docs/man3.0/
  home: https://www.openssl.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 76d06ce8-92b8-403b-aefb-2853fda01914
  recipe-maintainers:
    - carlodri
    - chenghlee
    - jakirkham
    - jjhelmus
    - msarahan
    - ocefpaf
    - pelson
  remote_url: git@github.com:AnacondaRecipes/openssl-feedstock.git
  sha: 772162b63626df93b2b6260cb4c3938d1add1eeb
